spring:
  application:
    name: SDU IT Park CRM
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/sdu_it_park_crm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

auth:
  token:
    secret: M2I1OWExNzFlNGRhOWRiMGZiM2FlM2E1ZjFkM2E4ZDI4YTg5ZTgwMjk0MmY1OGYyMzk0ZGVjYmY=
    access:
      expirationTime: 3600
    refresh:
      expirationTime: 2592000
